version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install awscli

      - run:
          name: zip artifact
          command: |
            pwd
            ls -al
            zip main.zip main.py
            ls -al

      - run:
          name: deploy
          command: |
            aws lambda update-function-code --function-name lambda_hello_world --zip-file fileb://main.zip