version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install awscli

      - run:
          name: zip artifact
          command: |
            pwd
            ls -al
            zip main.zip main.py
            ls -al

      - run:
          name: deploy
          context: AWS
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set default.region us-east-1

            aws lambda update-function-code --function-name lambda_hello_world --zip-file fileb://main.zip