version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: say hi
          command: |
            echo "Well Howdy!"

      - run:
          name: deployment
          command: |
            ls -al